version: "3"



services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=adminpass123
    volumes:
    - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "5432:5432"


  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
    - ./:/usr/src/app
    depends_on:
      - postgresdb
#    ports:
#    - "8000:8000"