# Generated by Django 3.0.8 on 2021-05-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
        ('mainapp', '0016_auto_20210525_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features_for_product', to='specs.ProductFeatures'),
        ),
    ]
